runtime: custom
api_version: go1
vm: true
module: module2

beta_settings:
  cloud_sql_instances: project-id:region:instance-name

manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: _go_app
